-- Criação de tabelas

CREATE TABLE TB_CLIENTES (

    CPF VARCHAR(11),
    NOME VARCHAR(100),
    ENDERECO1 VARCHAR(150),
    ENDERECO2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR(1),
    LIMITE_CREDITO NUMBER(15,2),
    PRIMEIRA_COMPRA NUMBER(1)

);

CREATE TABLE TB_VENDEDORES (

    MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER

);

CREATE TABLE TB_PRODUTOS (

    PRODUTO VARCHAR2(20),
    NOME VARCHAR2(150),
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(50),
    PRECO_LISTA NUMBER

);

-- Definir Chaves

    -- Informações no arquivo alterarTabela.sql